// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKb7VxR0VcodJD6nYLrWYwG12_PZgtnlY',
    appId: '1:93863055656:web:6535516853caaae667c01d',
    messagingSenderId: '93863055656',
    projectId: 'chatapp-95940',
    authDomain: 'chatapp-95940.firebaseapp.com',
    storageBucket: 'chatapp-95940.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlylr_vZAsaMfE29HJlbfgTa2tazX7CEE',
    appId: '1:93863055656:android:24e41c8c60c84e5767c01d',
    messagingSenderId: '93863055656',
    projectId: 'chatapp-95940',
    storageBucket: 'chatapp-95940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-2j7LkR2luSLFnCo3rECztGaP-P6qvM',
    appId: '1:93863055656:ios:6539ff5d51e2a8cd67c01d',
    messagingSenderId: '93863055656',
    projectId: 'chatapp-95940',
    storageBucket: 'chatapp-95940.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-2j7LkR2luSLFnCo3rECztGaP-P6qvM',
    appId: '1:93863055656:ios:6539ff5d51e2a8cd67c01d',
    messagingSenderId: '93863055656',
    projectId: 'chatapp-95940',
    storageBucket: 'chatapp-95940.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKb7VxR0VcodJD6nYLrWYwG12_PZgtnlY',
    appId: '1:93863055656:web:70d3bc604eacb09f67c01d',
    messagingSenderId: '93863055656',
    projectId: 'chatapp-95940',
    authDomain: 'chatapp-95940.firebaseapp.com',
    storageBucket: 'chatapp-95940.firebasestorage.app',
  );
}
